### PR TITLE
Badge component

### PR DESCRIPTION
**Pull request by pedrosantayana**
This PR implements the `<Badge>` component.

### CODE REVIEW

**Comment by isosphere** [comment]
Thank you for your contribution!

When I check the Bootstrap documentation on badges, I see a couple of examples of more advanced usage than you appear to have implemented. Have you given thought to the ["positioned" use case](https://getbootstrap.com/docs/5.1/components/badge/#positioned)?

**Comment by pedrosantayana** [comment]
I will try to implement. That's my first open source contribution, sorry about the incomplete PR.

**Comment by isosphere** [comment]
> I will try to implement. That's my first open source contribution, sorry about the incomplete PR.

Even incomplete PRs are welcome, they might just wait longer to merge. Contribute in any way you feel comfortable, thank you for contributing!

**Comment by pedrosantayana** [comment]
I've implemented the "positioned" use case, so you can review if it is alright or if it is missing something.

**Review by isosphere — APPROVED** [review]
Looks good! Thanks for completing the feature.

**Pull request merged**
