### PR TITLE
Form controls

### PR DESCRIPTION
**Pull request by dricair**
Proposal to add form inputs, including Select.

Feedback welcome as I am still very new to Rust.

### CODE REVIEW

**Comment by isosphere** [comment]
Thank you for your contribution!

Looks like the examples you've included in your doc strings can't be compiled, see ["Details"](https://github.com/isosphere/yew-bootstrap/actions/runs/4236757898/jobs/7361932233) for the automated check results. These examples are automatically tested to ensure they are not broken by future changes. 

You can hide portions of these examples for brevity if you like the "to the point" approach, see [here](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example)!

**Comment by dricair** [comment]
Yes I forgot to run cargo test, I will fix it.

Cédric

**Comment by isosphere** [comment]
I think it might be clearer for us to refer to form feedback as "form validation", as it'll be more clear I think. I was pretty sure I knew what you meant, but it took me a bit to verify that. Unless I've missed some standard vocabulary used with bootstrap or yew or some-such that would explain the choice.

**Comment by dricair** [comment]
I agree it would make sense. I got the term from the bootstrap page:
https://getbootstrap.com/docs/5.3/forms/validation/

But it's true it mostly speaks about "validation", and "feedback" is only
the message. I will do the changes to call it Validation.

**Comment by isosphere** [comment]
Please try to avoid using force-push if you can, it makes reviewing the code more difficult. Sometimes it's necessary, but it looks like you might be using it by default.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

> Be very careful when force pushing commits to a pull request. Force pushing changes the repository history and can corrupt your pull request. If other collaborators branch the project before a force push, the force push may overwrite commits that collaborators based their work on.

**Comment by dricair** [comment]
Ok. Yes I almost always use force-push to avoid commits that "fix" another
commit.
I can change it.

**Comment by isosphere** [comment]
Thanks! It was breaking the commit tree on my dev machine; you can alter history on your own all you want, but once you've pushed it somewhere else that's set in stone!

Your contribution has triggered me to do a refactor that'll make everyone's lives easier in the future, I think. We need to separate our examples from the core library, just as yew does.  

This will allow you to have your own example project in an examples directory that can have its own dependencies. The existing example we have is already pretty big, and I think we should stop adding to it in favour of separating things out for clarity and brevity. 

I will modify your PR accordingly, because it'll be pretty broken and it's my fault!

**Comment by isosphere** [comment]
I couldn't get git to merge with this commit tree, so I created a new branch and did the work there. 

Please see PR #9; it is this same code with several edits.

**Comment by dricair** [comment]
Ok thanks.

One modification I envisaged (If it's the one you describe) is to move
example to "examples/" directory, so that we could add dependencies which
are specific to this example. What I was not able to do however was to
explain trunk serve to use this example (But did not spend much time).

**Pull request closed without merging**
