### PR TITLE
Add Progress and ProgressBar components

### PR DESCRIPTION
**Pull request by dricair**
In line with https://getbootstrap.com/docs/4.0/components/progress/

### CODE REVIEW

**Review by isosphere — CHANGES_REQUESTED** [review]
Thanks for another contribution!

While I agree with error checking, I don't love being a library  that `panic!`s when bounds are exceeded. This could conceivably happen if the value is bound and modified to be out of bounds. I think I'd rather we clamp the value to be max if it's above max and ditto for min and complain with a console error somewhere. The entire Yew application we provide components for shouldn't crash for this kind of violation.

**Comment by dricair** [comment]
Ok I think you're right. I tried to not change the values as much as possible except to avoid the div to panic.
Note that warn does not print anything, I think we should replace by `gloo::console` instead to display on the browser console.

**Comment by isosphere** [comment]
>  I think we should replace by `gloo::console` instead to display on the browser console.

I agree! That's a pretty common dependency, I think it's reasonable for us to depend on it so we can provide better debugging info.

**Comment by dricair** [comment]
I added a commit to change log::warn to gloo_console::warn.
It is almost directly compatible except that later do not do `format!` itself.

**Comment by isosphere** [comment]
Thanks for the adjustment; merged with main as 0.9.0.

I feel the bump in minor version coveys the new feature supported better.

**Pull request merged**
