### PR TITLE
Update to Yew 0.19

### PR DESCRIPTION
**Pull request by intgr**
According to the conversion guide https://yew.rs/docs/next/migration-guides/yew/from-0_18_0-to-0_19_0 and some trial and error. Seems to work.

### CODE REVIEW

**Comment by Foorack** [comment]
Thanks a lot! <3

**Comment by Foorack** [comment]
Will release an update to cargo later today.

**Comment by Foorack** [comment]
@intgr 0.4.0 has now been pushed.

**Comment by intgr** [comment]
Thanks!

**Pull request merged**
